name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js with the specified version
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Lint the code to check for code style issues
      - name: Check style
        run: npm run eslint

      # Step 5: Build the project for production
      - name: Build the project
        run: npm run build

      # Step 6: Run tests to ensure everything works as expected
      - name: Run tests
        run: npm test
